version: '2'
services:
  mongodb:
    command: "--rest"
    hostname: my-mongo
    image: mongo:3.2
    ports:
      - "27017:27017"
      - "28017:28017"
  calculator-service:
    image: devtoolindex/calculator-service:2.3
    ports:
      - "8090:8090"
    links:
      - mongodb
