mongodb:
  command: "--rest"
  hostname: my-mongo
  image: mongo:3.2
  ports:
    - "27017:27017"
    - "28017:28017"
calculator-service:
  image: devtoolindex/calculator-service:3.1
  ports:
    - "8090:8080"
  links:
    - mongodb
